services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proyek-app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/proyek_ws
      - MIDTRANS_SERVER_KEY=${MIDTRANS_SERVER_KEY}
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    depends_on:
      - app
    command: http app:3000
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040" # Untuk akses dasbor ngrok

volumes:
  mongo-data:
